/*
 * spi_rx.c
 *
 *  Created on: Jul 6, 2026
 *      Author: nachiket
 */


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// SPI1_NSS ====> PA4
// SPI1_SCK ====> PA5
// SPI1_MISO ====> PA6
// SPI1_MOSI ====> PA7

#include "main.h"

SPI_Handle_t SPI1_Handle;

volatile char ReadByte;

volatile uint8_t rcvStop = 0;

/*This flag will be set in the interrupt handler of the Arduino interrupt GPIO */
volatile uint8_t dataAvailable = 0;

int main(void)
{
	uint8_t dummy = 0xff;

	Slave_GPIO_InterruptPinInit();

	//Gpio config for spi
	SPI_GPIOInits();

	//gpio button config
	GPIO_ButtonInit();

	//spi1 peripheral config and initialisation
	SPI1_Inits();

	//this makes nss internally high avoiding modf error
	//SPI_SSIConfig(SPI1, ENABLE);

	//this outputs 0 from nss the moment spi peripheral is turned on
	SPI_SSOEConfig(SPI1, ENABLE);

	SPI_IRQInterruptConfig(IRQ_NO_SPI1,ENABLE);

	//button pin config
	GPIO_ButtonInit();

	while(1){

		rcvStop = 0;

		while(!dataAvailable); //wait till data available interrupt from transmitter device(slave)

		GPIO_IRQInterruptConfig(IRQ_NO_EXTI0,DISABLE);

		//enable the SPI2 peripheral
		SPI_PeripheralControl(SPI1,ENABLE);

		while(!rcvStop)
		{
			/* fetch the data from the SPI peripheral byte by byte in interrupt mode */
			while ( SPI_SendDataIT(&SPI1_Handle,&dummy,1) == SPI_BUSY_IN_TX);
			while ( SPI_ReceiveDataIT(&SPI1_Handle,(uint8_t*)&ReadByte,1) == SPI_BUSY_IN_RX );
		}

		// confirm SPI is not busy
		while( SPI_GetFlagStatus(SPI1,SPI_BUSY_FLAG) );

		//Disable the SPI2 peripheral
		SPI_PeripheralControl(SPI1,DISABLE);

		printf("Rcvd data = %s\n",RcvBuff);

		memset(RcvBuff, 0, sizeof(RcvBuff));

		dataAvailable = 0;

		GPIO_IRQInterruptConfig(IRQ_NO_EXTI0,ENABLE);
	}
}

/* Peripheral and GPIO configurations */
void SPI_GPIOInits(void)
{
	GPIO_Handle_t SPIPins;

	SPIPins.pGPIOx=GPIOA;
	SPIPins.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_ALTFN;
	SPIPins.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
	SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD;
	SPIPins.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_HIGH;
	SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode=5;

	//SPI1_NSS
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_4;
	GPIO_Init(&SPIPins);

	//SPI1_SCK
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_5;
	GPIO_Init(&SPIPins);

	//SPI1_MISO
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_6;
	GPIO_Init(&SPIPins);

	//SPI1_MOSI
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_7;
	GPIO_Init(&SPIPins);
}

void SPI1_Inits(void)
{
	SPI1_Handle.pSPIx=SPI1;

	SPI1_Handle.SPIConfig.SPI_BusConfig=SPI_BUS_CONFIG_FD;
	SPI1_Handle.SPIConfig.SPI_DeviceMode=SPI_DEVICE_MODE_MASTER;
	SPI1_Handle.SPIConfig.SPI_SclkSpeed=SPI_SCLK_SPEED_DIV2; //8mhz sclk
	SPI1_Handle.SPIConfig.SPI_DFF=SPI_DFF_8BITS;
	SPI1_Handle.SPIConfig.SPI_CPHA=SPI_CPHA_LOW;
	SPI1_Handle.SPIConfig.SPI_CPOL=SPI_CPOL_LOW;
	SPI1_Handle.SPIConfig.SPI_SSM=SPI_SSM_DI; //hardware slave management enabled for nss pin

	SPI_Init(&SPI1_Handle);
}

void GPIO_ButtonInit(void)
{
	GPIO_Handle_t GPIOBtn;

	//this is btn gpio configuration
	GPIOBtn.pGPIOx = GPIOC;
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&GPIOBtn);
}

void Slave_GPIO_InterruptPinInit(void)
{
	GPIO_Handle_t spiIntPin;
	memset(&spiIntPin,0,sizeof(spiIntPin));

	//this is led gpio configuration
	spiIntPin.pGPIOx = GPIOC;
	spiIntPin.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	spiIntPin.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_RT;
	spiIntPin.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	spiIntPin.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;

	GPIO_Init(&spiIntPin);

	GPIO_IRQPriorityConfig(IRQ_NO_EXTI0, NVIC_IRQ_PRIO15);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI0, ENABLE);
}

void SPI1_IRQHandler(void)
{
	SPI_IRQHandling(&SPI1_Handle);
}

/* Slave data available interrupt handler */
void EXTI0_IRQHandler(void)
{
	GPIO_IRQHandling(GPIO_PIN_NO_0);
	dataAvailable = 1;
}

void SPI_ApplicationEventCallback(SPI_Handle_t *pHandle,uint8_t AppEv)
{
	static uint32_t i = 0;
	/* In the RX complete event , copy data in to rcv buffer . '\0' indicates end of message(rcvStop = 1) */
	if(AppEv == SPI_EVENT_RX_CMPLT)
	{
		RcvBuff[i++] = ReadByte;
		if(ReadByte == '\0' || ( i == MAX_LEN))
		{
			rcvStop = 1;
			RcvBuff[i-1] = '\0';
			i = 0;
		}
	}
}

void delay(void)
{
	for(uint32_t i=0;i<500000/2;i++);
}

