/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// SPI1_NSS ====> PA4
// SPI1_SCK ====> PA5
// SPI1_MISO ====> PA6
// SPI1_MOSI ====> PA7

#include "main.h"

SPI_Handle_t SPI1_Handle;

int main(void)
{
	uint8_t user_data[32]="Transmitting data from nucleo";

	//Gpio config for spi
	SPI_GPIOInits();

	//gpio button config
	GPIO_ButtonInit();

	//spi1 peripheral config and initialisation
	SPI1_Inits();

	//this makes nss internally high avoiding modf error
	//SPI_SSIConfig(SPI1, ENABLE);

	//this outputs 0 from nss the moment spi peripheral is turned on
	SPI_SSOEConfig(SPI1, ENABLE);

	//button pin config
	GPIO_ButtonInit();

	while(1)
	{

		//check for button press
		while(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13));
		delay();

		//enabling the spi peripheral
		SPI_PeripheralControl(SPI1, ENABLE);

		//send data
		SPI_SendData(SPI1, (uint8_t*)user_data, 32);

		//lets confirm spi is not busy
		while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));

		//disable spi1 peripheral
		SPI_PeripheralControl(SPI1, DISABLE);
	}
}

/* Peripheral and GPIO configurations */
void SPI_GPIOInits(void)
{
	GPIO_Handle_t SPIPins;

	SPIPins.pGPIOx=GPIOA;
	SPIPins.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_ALTFN;
	SPIPins.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
	SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD;
	SPIPins.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_HIGH;
	SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode=5;

	//SPI1_NSS
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_4;
	GPIO_Init(&SPIPins);

	//SPI1_SCK
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_5;
	GPIO_Init(&SPIPins);

	//SPI1_MISO
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_6;
	GPIO_Init(&SPIPins);

	//SPI1_MOSI
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_7;
	GPIO_Init(&SPIPins);
}

void SPI1_Inits(void)
{
	SPI1_Handle.pSPIx=SPI1;

	SPI1_Handle.SPIConfig.SPI_BusConfig=SPI_BUS_CONFIG_FD;
	SPI1_Handle.SPIConfig.SPI_DeviceMode=SPI_DEVICE_MODE_MASTER;
	SPI1_Handle.SPIConfig.SPI_SclkSpeed=SPI_SCLK_SPEED_DIV2; //8mhz sclk
	SPI1_Handle.SPIConfig.SPI_DFF=SPI_DFF_8BITS;
	SPI1_Handle.SPIConfig.SPI_CPHA=SPI_CPHA_LOW;
	SPI1_Handle.SPIConfig.SPI_CPOL=SPI_CPOL_LOW;
	SPI1_Handle.SPIConfig.SPI_SSM=SPI_SSM_DI; //hardware slave management enabled for nss pin

	SPI_Init(&SPI1_Handle);
}

void GPIO_ButtonInit(void)
{
	GPIO_Handle_t GPIOBtn;

	//this is btn gpio configuration
	GPIOBtn.pGPIOx = GPIOC;
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&GPIOBtn);
}

void delay(void)
{
	for(uint32_t i=0;i<500000/2;i++);
}

