/*
 * spi_command_handling.c
 *
 *  Created on: Jul 4, 2026
 *      Author: nachiket
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// SPI1_NSS ====> PA4
// SPI1_SCK ====> PA5
// SPI1_MISO ====> PA6
// SPI1_MOSI ====> PA7

#include "main.h"

SPI_Handle_t SPI1_Handle;

uint8_t dummy_write=0xff;
uint8_t dummy_read;

int main(void)
{
	//Gpio config for spi
	SPI_GPIOInits();

	//gpio button config
	GPIO_ButtonInit();

	//spi1 peripheral config and initialisation
	SPI1_Inits();

	//this makes nss internally high avoiding modf error
	//SPI_SSIConfig(SPI1, ENABLE);

	//this outputs 0 from nss the moment spi peripheral is turned on
	SPI_SSOEConfig(SPI1, ENABLE);

	//button pin config
	GPIO_ButtonInit();

	while(1)
	{
		//wait until button is pressed
	    while(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13));
	    delay(); //to avoid de bouncing issues

	    //1. Sends led pin no and on/off command
	    // CMD_LED_CONTROL <pin no> <led on/off>
	    led_control();

	    delay();

	    //wait until button is pressed
	    while(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13));
	    delay(); //to avoid de bouncing issues

	    //2. CMD_SENSOR_READ <analog pin no>
	    sensor_read();

	    //wait until button is pressed
	    while(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13));
	    delay(); //to avoid de bouncing issues

	    //3. COMMAND_LED_READ <pin no>
	    led_read();

	    //wait until button is pressed
	    while(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13));
	    delay(); //to avoid de bouncing issues

	    //4. COMMAND_ID_READ
	    id_read();

	    //wait until button is pressed
	    while(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13));
	    delay(); //to avoid de bouncing issues

	    //5. COMMAND_PRINT
	    print();

	    delay();
	}
}

void id_read(void)
{
    uint8_t commandcode = COMMAND_ID_READ;
    uint8_t ackbyte;
    uint8_t id_buf[16] = {0};   // big enough for "ESP32WROOM" + margin
    uint8_t id_dummy[16] = {0xff};   // big enough for "ESP32WROOM" + margin

    // ---- CS pulse 1: send command ----
    delay();

    SPI_PeripheralControl(SPI1, ENABLE);

    SPI_SendData(SPI1, &commandcode, 1);
    SPI_ReceiveData(SPI1, &dummy_read, 1);

    while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
    SPI_PeripheralControl(SPI1, DISABLE);

    delay();

    // ---- CS pulse 2: fetch ack ----
    SPI_PeripheralControl(SPI1, ENABLE);

    SPI_SendData(SPI1, &dummy_write, 1);
    SPI_ReceiveData(SPI1, &ackbyte, 1);

    while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
    SPI_PeripheralControl(SPI1, DISABLE);

    delay();

    if(SPI_VerifyResponse(ackbyte))
    {
        printf("Testing id read command\n");
        printf("CONFIRMATION BYTE RECEIVED FROM ESP: ACK\n");

        uint8_t id_len = 10;   // strlen("ESP32WROOM") -- must match the ESP32 side exactly

        // ---- CS pulse 3: fetch the ID string ----
        SPI_PeripheralControl(SPI1, ENABLE);

        for(int i = 0; i < 11; i++)
        {
        	SPI_SendData(SPI1, &id_dummy[i], 1);
        	SPI_ReceiveData(SPI1, &id_buf[i], 1);
        }

        id_buf[id_len] = '\0';
        printf("ID received: %s\n", id_buf);
    }
    delay();
}

void print(void)
{
    uint8_t commandcode = COMMAND_PRINT;
    uint8_t ackbyte;
    uint8_t user_data[32]="Transmitting data from nucleo";

    // ---- CS pulse 1: send command ----
    delay();
    SPI_PeripheralControl(SPI1, ENABLE);

    SPI_SendData(SPI1, &commandcode, 1);
    SPI_ReceiveData(SPI1, &dummy_read, 1);

    while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
    SPI_PeripheralControl(SPI1, DISABLE);

    delay();

    // ---- CS pulse 2: fetch ack ----
    SPI_PeripheralControl(SPI1, ENABLE);

    SPI_SendData(SPI1, &dummy_write, 1);
    SPI_ReceiveData(SPI1, &ackbyte, 1);

    while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
    SPI_PeripheralControl(SPI1, DISABLE);

    delay();

    if(SPI_VerifyResponse(ackbyte))
    {
        printf("Testing print command\n");
        printf("CONFIRMATION BYTE RECEIVED FROM ESP: ACK\n");
        uint8_t len = strlen((char*)user_data);

        // ---- CS pulse 3: send args ----
        delay();

        SPI_PeripheralControl(SPI1, ENABLE);

        SPI_SendData(SPI1, &len, 1);
        SPI_ReceiveData(SPI1, &dummy_read, 1); //clear rxne after sending args

        while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
        SPI_PeripheralControl(SPI1, DISABLE);

        delay();

        SPI_PeripheralControl(SPI1, ENABLE);

        //static uint8_t rx_dump[32];
        SPI_SendData(SPI1, user_data, len);
        //SPI_ReceiveData(SPI1, rx_dump, len);

        while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
        SPI_PeripheralControl(SPI1, DISABLE);
    }
    delay();
}

void led_read(void)
{
    uint8_t commandcode = COMMAND_LED_READ;
    uint8_t ackbyte;
    uint8_t args[1];
    uint8_t led_read=0;

    // ---- CS pulse 1: send command ----
    SPI_PeripheralControl(SPI1, ENABLE);

    SPI_SendData(SPI1, &commandcode, 1);
    SPI_ReceiveData(SPI1, &dummy_read, 1);

    while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
    SPI_PeripheralControl(SPI1, DISABLE);

    delay();

    // ---- CS pulse 2: fetch ack ----
    SPI_PeripheralControl(SPI1, ENABLE);

    SPI_SendData(SPI1, &dummy_write, 1);
    SPI_ReceiveData(SPI1, &ackbyte, 1);

    while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
    SPI_PeripheralControl(SPI1, DISABLE);

    delay();

    if(SPI_VerifyResponse(ackbyte))
    {
    	printf("Testing LED READ\n");
        printf("CONFIRMATION BYTE RECEIVED FROM ESP: ACK\n");
        args[0] = LED_PIN;

        // ---- CS pulse 3: send args ----
        SPI_PeripheralControl(SPI1, ENABLE);

        SPI_SendData(SPI1, args, 1);
        SPI_ReceiveData(SPI1, &dummy_read, 1); //clear rxne after sending args

        while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
        SPI_PeripheralControl(SPI1, DISABLE);

        delay();

        SPI_PeripheralControl(SPI1, ENABLE);

        SPI_SendData(SPI1, &dummy_write, 1); //dummy byte sent to receive the response from the slave
        SPI_ReceiveData(SPI1, &led_read, 1);

        while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
        SPI_PeripheralControl(SPI1, DISABLE);

        printf("LED state of pin %u: %u \n", LED_PIN, led_read);
    }
    delay();
}

void sensor_read(void)
{
    uint8_t commandcode = COMMAND_SENSOR_READ;
    uint8_t ackbyte;
    uint8_t args[1];
    uint8_t analog_read;

    // ---- CS pulse 1: send command ----
    delay();

    SPI_PeripheralControl(SPI1, ENABLE);

    SPI_SendData(SPI1, &commandcode, 1);
    SPI_ReceiveData(SPI1, &dummy_read, 1);

    while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
    SPI_PeripheralControl(SPI1, DISABLE);

    delay();

    // ---- CS pulse 2: fetch ack ----
    SPI_PeripheralControl(SPI1, ENABLE);

    SPI_SendData(SPI1, &dummy_write, 1);
    SPI_ReceiveData(SPI1, &ackbyte, 1);

    while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
    SPI_PeripheralControl(SPI1, DISABLE);

    delay();

    if(SPI_VerifyResponse(ackbyte))
    {
    	printf("Testing SENSOR READ\n");
        printf("CONFIRMATION BYTE RECEIVED FROM ESP: ACK\n");
        args[0] = ANALOG_PIN0;

        // ---- CS pulse 3: send args ----
        SPI_PeripheralControl(SPI1, ENABLE);

        SPI_SendData(SPI1, args, 1);
        SPI_ReceiveData(SPI1, &dummy_read, 1); //clear rxne after sending args

        while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
        SPI_PeripheralControl(SPI1, DISABLE);

        delay();

        SPI_PeripheralControl(SPI1, ENABLE);

        SPI_SendData(SPI1, &dummy_write, 1); //dummy byte sent to receive the response from the slave
        SPI_ReceiveData(SPI1, &analog_read, 1);

        while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
        SPI_PeripheralControl(SPI1, DISABLE);

        printf("Status of the sensor: %u \n", analog_read);
    }
    delay();
}

void led_control(void)
{
    uint8_t commandcode = COMMAND_LED_CTRL;
    uint8_t ackbyte;
    uint8_t args[2];

    // ---- CS pulse 1: send command ----
    SPI_PeripheralControl(SPI1, ENABLE);

    SPI_SendData(SPI1, &commandcode, 1);
    SPI_ReceiveData(SPI1, &dummy_read, 1);

    while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
    SPI_PeripheralControl(SPI1, DISABLE);

    delay();

    // ---- CS pulse 2: fetch ack ----
    SPI_PeripheralControl(SPI1, ENABLE);

    SPI_SendData(SPI1, &dummy_write, 1);
    SPI_ReceiveData(SPI1, &ackbyte, 1);

    while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
    SPI_PeripheralControl(SPI1, DISABLE);

    delay();

    if(SPI_VerifyResponse(ackbyte))
    {
    	printf("Testing LED WRITE\n");
        printf("CONFIRMATION BYTE RECEIVED FROM ESP: ACK\n");
        args[0] = LED_PIN;
        args[1] = LED_ON;

        // ---- CS pulse 3: send args ----
        SPI_PeripheralControl(SPI1, ENABLE);

        SPI_SendData(SPI1, args, 2);
        //SPI_ReceiveData(SPI1, &dummy_read, 2); //clear the rxne flag

        while(SPI_GetFlagStatus(SPI1, SPI_BUSY_FLAG));
        SPI_PeripheralControl(SPI1, DISABLE);
    }
    delay();
}
/* Peripheral and GPIO configurations */
void SPI_GPIOInits(void)
{
	GPIO_Handle_t SPIPins;

	SPIPins.pGPIOx=GPIOA;
	SPIPins.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_ALTFN;
	SPIPins.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
	SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD;
	SPIPins.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_HIGH;
	SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode=5;

	//SPI1_NSS
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_4;
	GPIO_Init(&SPIPins);

	//SPI1_SCK
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_5;
	GPIO_Init(&SPIPins);

	//SPI1_MISO
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_6;
	GPIO_Init(&SPIPins);

	//SPI1_MOSI
	SPIPins.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_7;
	GPIO_Init(&SPIPins);
}

void SPI1_Inits(void)
{
	SPI1_Handle.pSPIx=SPI1;

	SPI1_Handle.SPIConfig.SPI_BusConfig=SPI_BUS_CONFIG_FD;
	SPI1_Handle.SPIConfig.SPI_DeviceMode=SPI_DEVICE_MODE_MASTER;
	SPI1_Handle.SPIConfig.SPI_SclkSpeed=SPI_SCLK_SPEED_DIV2; //8mhz sclk
	SPI1_Handle.SPIConfig.SPI_DFF=SPI_DFF_8BITS;
	SPI1_Handle.SPIConfig.SPI_CPHA=SPI_CPHA_LOW;
	SPI1_Handle.SPIConfig.SPI_CPOL=SPI_CPOL_LOW;
	SPI1_Handle.SPIConfig.SPI_SSM=SPI_SSM_DI; //hardware slave management enabled for nss pin

	SPI_Init(&SPI1_Handle);
}

int SPI_VerifyResponse(uint8_t ackbyte)
{
	if(ackbyte==0xF5)
	{
		return 1;
	}
	return 0;
}

void GPIO_ButtonInit(void)
{
	GPIO_Handle_t GPIOBtn;

	//this is btn gpio configuration
	GPIOBtn.pGPIOx = GPIOC;
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&GPIOBtn);
}

void delay(void)
{
	for(uint32_t i=0;i<500000/2;i++);
}


